# 1. אל תשתמש בקובץ ה-hosts של השרת השרת עצמו
no-hosts

# 2. שרתי ה-DNS החיצוניים לאינטרנט רגיל (שרידות של גוגל וקלאודפלייר)
server=8.8.8.8
server=1.1.1.1

# 3. חוק הקסם: הפנה את כל הכתובות של הארכיון ל-Localhost של המחשב
address=/.fcms.local/127.0.0.1